### ISSUE TITLE
Голосование доступно по старой ссылке после завершения голосования.

### ISSUE THREAD

**Issue by SaGite** [NewCyberState/OGAS#2]
В завершенном голосовании, можно доголосовать, если зайти по старой ссылке.

Если заходить через меню, то зайдешь на https://ogasdemo.ru/lkg/gos/law/rejected/102/, и здесь только результаты.

А если прямо по старой ссылке, сохраненной на промежуточном этапе, например, https://ogasdemo.ru/lkg/gos/referendum/102/, тогда и заголовок "Идет референдум", и, если еще не голосовал, можно до-роголосовать. И если проголосовать, результаты даже обновятся!

Старых ссылок будет по ходу дела в сети, в постах и старых сообщениях, накапливаться множество, так что проблема серьезная.

**Comment by NewCyberState** [comment]
Пофиксил.
